# Generated by Django 5.0.6 on 2025-08-09 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10)),
                ('text', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50)),
                ('background_color', models.CharField(default='#3b82f6', max_length=7)),
                ('visibility', models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'My Contacts'), ('custom', 'Custom')], default='everyone', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'status_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('❤️', 'Heart'), ('😂', 'Laugh'), ('😮', 'Wow'), ('😢', 'Sad'), ('😡', 'Angry'), ('👍', 'Like'), ('👎', 'Dislike')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='user_status.statusupdate')),
            ],
            options={
                'db_table': 'status_reactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='user_status.statusupdate')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'status_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_viewers', to='user_status.statusupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'status_viewers',
            },
        ),
        migrations.AddIndex(
            model_name='statusupdate',
            index=models.Index(fields=['owner', '-created_at'], name='status_upda_owner_i_51133c_idx'),
        ),
        migrations.AddIndex(
            model_name='statusupdate',
            index=models.Index(fields=['expires_at'], name='status_upda_expires_b74503_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statusreaction',
            unique_together={('status', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='statusview',
            unique_together={('status', 'viewer')},
        ),
        migrations.AlterUniqueTogether(
            name='statusviewer',
            unique_together={('status', 'user')},
        ),
    ]
